const { title } = require("process");

const jsonData = {
    "kind": "youtube#videoListResponse",
    "etag": "NotImplemented",
    "items": [
        {
            "kind": "youtube#video",
            "etag": "NotImplemented",
            "id": "aaaaa",
            "chapters": {
                "areAutoGenerated": false,
                "chapters": [
                    {
                        "title": "0. I'm Coming Home (Stayer, CPX, Rachel Morgan Perry Cover) (Magic Cover Release)",
                        "time": 0,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "1. Cabuizee, Protocleus, Lyra D. - The Reason",
                        "time": 137,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "2. Antomage & Sarah de Warren - Astronomy ( Magic & Nightblue Co-release)",
                        "time": 300,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "3. 3. Harddope, LexMorris, Nito-Onna - New Divide",
                        "time": 440,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "4. Coopex & Yohan Gerber - Radioactive (ft. LUNIS)",
                        "time": 598,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "5. Too Close (Twin, MelonColly Cover) (Magic Cover Release)",
                        "time": 755,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "6. Dame Dame - This Is What You Came For (MASTER)",
                        "time": 930,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "7. Arc North, New Beat Order, Cour & Aaron Richards - Numb",
                        "time": 1071,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "8. 08 BIMONTE & JANFRY - In The End",
                        "time": 1198,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "9. Arc North, Meric Again, Fallen Roses - Enemy",
                        "time": 1364,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "10. 9. PACANI, Leddo, MelonColly - Demons (Cover)",
                        "time": 1503,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "11. Robbe, DJSM, CPX - Sweet But Psycho (ft. Britt Lari)",
                        "time": 1655,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "12. 049. Robbe x New Beat Order x Britt Lari - Kings & Queens",
                        "time": 1811,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "13. Sweater Weather (PACANI, BEX Cover) (Magic Cover Release)",
                        "time": 1967,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "14. Dame Dame, Lunis - Beggin",
                        "time": 2103,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "15. 01 CPX & HUX - Inferno (online-audio-converter.com)",
                        "time": 2251,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "16. 11 Harddope, The Kith - Nightlight",
                        "time": 2375,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "17. Yohan Gerber, NE\u00d8N, Jason Wats - Rescue Me (Ft.J R)",
                        "time": 2503,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "18. Alban Chela & Marin Hoxha - Thousand Years (Magic Free Release)",
                        "time": 2629,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "19. Meric Again, 22Angels - Universe",
                        "time": 2788,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "20. Protocleus & Edpranz & Leila - Tired",
                        "time": 2914,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "21. R3YAN & Benlon - The Business",
                        "time": 3077,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "22. New Rules (EQRIC, PHARA\u00d8H, Whoopa Cover)",
                        "time": 3233,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "23. Girls Like You (2Shy, Ben Plum, PACANI Cover) (Magic Cover Release)",
                        "time": 3361,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "24. Applause (EQRIC, Kverz, Alaina Cross Cover) (Magic Cover Release)",
                        "time": 3505,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "25. Lily (ISAEV, PACANI, Jessica Chertock Cover)",
                        "time": 3664,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "26. 4. Ericovich - Go Go Go Go!",
                        "time": 3818,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "27. 3. Yohan Gerber, Bersage, HALUNA - Unfaithful",
                        "time": 3938,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "28. 18. New Beat Order, NEMESIS & Rachel Morgan Perry - The Nights",
                        "time": 4092,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    },
                    {
                        "title": "29. ONEIL, KANVISE, Yovalia - Rampampam (Magic Cover Release)",
                        "time": 4233,
                        "thumbnails": [
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEiCKgBEF5IWvKriqkDFQgBFQAAAAAYASUAAMhCPQCAokN4AQ==&rs=AOn4CLCPYdgN8vdy2-sUA1b29d1KvwrspQ",
                                "width": 168,
                                "height": 94
                            },
                            {
                                "url": "https:\/\/i.ytimg.com\/vi\/62BQwujARmU\/hqdefault.jpg?sqp=-oaymwEjCNACELwBSFryq4qpAxUIARUAAAAAGAElAADIQj0AgKJDeAE=&rs=AOn4CLA2M9whpmRFMqXYP5zvfwaZkMIezg",
                                "width": 336,
                                "height": 188
                            }
                        ]
                    }
                ]
            }
        }
    ]
};

const retorno = jsonData.items.map(item => item.chapters.chapters);
const titlesArray = [];

// Percorrer a lista de músicas e extrair os títulos
retorno.forEach((musicList) => {
  musicList.forEach((music) => {
    titlesArray.push(music.title);
  });
});

console.log(titlesArray);